baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'gumperto.github.io'

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
        [markup.goldmark.extenstions]
            [markup.goldmark.extensions.typographer]
                disable = true

[params]
    mainSections = ["articles","process","fiction"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

enableGitInfo = true
