baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'gumperto.github.io'

[markup.goldmark.parser.attribute]
    block = true

[params]
    mainSections = ["articles","process","fiction"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
